ds_course = [['Machine Learning Crash Course by Google [Free]', 'https://developers.google.com/machine-learning/crash-course'],
             ['Machine Learning A-Z by Udemy','https://www.udemy.com/course/machinelearning/'],
             ['Machine Learning by Andrew NG','https://www.coursera.org/learn/machine-learning'],
             ['Data Scientist Master Program of Simplilearn (IBM)','https://www.simplilearn.com/big-data-and-analytics/senior-data-scientist-masters-program-training'],
             ['Data Science Foundations: Fundamentals by LinkedIn','https://www.linkedin.com/learning/data-science-foundations-fundamentals-5'],
             ['Data Scientist with Python','https://www.datacamp.com/tracks/data-scientist-with-python'],
             ['Programming for Data Science with Python','https://www.udacity.com/course/programming-for-data-science-nanodegree--nd104'],
             ['Programming for Data Science with R','https://www.udacity.com/course/programming-for-data-science-nanodegree-with-R--nd118'],
             ['Introduction to Data Science','https://www.udacity.com/course/introduction-to-data-science--cd0017'],
             ['Intro to Machine Learning with TensorFlow','https://www.udacity.com/course/intro-to-machine-learning-with-tensorflow-nanodegree--nd230']]

web_course = [['Django Crash course [Free]','https://youtu.be/e1IyzVyrLSU'],
              ['Python and Django Full Stack Web Developer Bootcamp','https://www.udemy.com/course/python-and-django-full-stack-web-developer-bootcamp'],
              ['React Crash Course [Free]','https://youtu.be/Dorf8i6lCuk'],
              ['ReactJS Project Development Training','https://www.dotnettricks.com/training/masters-program/reactjs-certification-training'],
              ['Full Stack Web Developer - MEAN Stack','https://www.simplilearn.com/full-stack-web-developer-mean-stack-certification-training'],
              ['Node.js and Express.js [Free]','https://youtu.be/Oe421EPjeBE'],
              ['Flask: Develop Web Applications in Python','https://www.educative.io/courses/flask-develop-web-applications-in-python'],
              ['Full Stack Web Developer by Udacity','https://www.udacity.com/course/full-stack-web-developer-nanodegree--nd0044'],
              ['Front End Web Developer by Udacity','https://www.udacity.com/course/front-end-web-developer-nanodegree--nd0011'],
              ['Become a React Developer by Udacity','https://www.udacity.com/course/react-nanodegree--nd019']]

android_course = [['Android Development for Beginners [Free]','https://youtu.be/fis26HvvDII'],
                  ['Android App Development Specialization','https://www.coursera.org/specializations/android-app-development'],
                  ['Associate Android Developer Certification','https://grow.google/androiddev/#?modal_active=none'],
                  ['Become an Android Kotlin Developer by Udacity','https://www.udacity.com/course/android-kotlin-developer-nanodegree--nd940'],
                  ['Android Basics by Google','https://www.udacity.com/course/android-basics-nanodegree-by-google--nd803'],
                  ['The Complete Android Developer Course','https://www.udemy.com/course/complete-android-n-developer-course/'],
                  ['Building an Android App with Architecture Components','https://www.linkedin.com/learning/building-an-android-app-with-architecture-components'],
                  ['Android App Development Masterclass using Kotlin','https://www.udemy.com/course/android-oreo-kotlin-app-masterclass/'],
                  ['Flutter & Dart - The Complete Flutter App Development Course','https://www.udemy.com/course/flutter-dart-the-complete-flutter-app-development-course/'],
                  ['Flutter App Development Course [Free]','https://youtu.be/rZLR5olMR64']]

ios_course = [['IOS App Development by LinkedIn','https://www.linkedin.com/learning/subscription/topics/ios'],
              ['iOS & Swift - The Complete iOS App Development Bootcamp','https://www.udemy.com/course/ios-13-app-development-bootcamp/'],
              ['Become an iOS Developer','https://www.udacity.com/course/ios-developer-nanodegree--nd003'],
              ['iOS App Development with Swift Specialization','https://www.coursera.org/specializations/app-development'],
              ['Mobile App Development with Swift','https://www.edx.org/professional-certificate/curtinx-mobile-app-development-with-swift'],
              ['Swift Course by LinkedIn','https://www.linkedin.com/learning/subscription/topics/swift-2'],
              ['Objective-C Crash Course for Swift Developers','https://www.udemy.com/course/objectivec/'],
              ['Learn Swift by Codecademy','https://www.codecademy.com/learn/learn-swift'],
              ['Swift Tutorial - Full Course for Beginners [Free]','https://youtu.be/comQ1-x2a1Q'],
              ['Learn Swift Fast - [Free]','https://youtu.be/FcsY1YPBwzQ']]
uiux_course = [['Google UX Design Professional Certificate','https://www.coursera.org/professional-certificates/google-ux-design'],
               ['UI / UX Design Specialization','https://www.coursera.org/specializations/ui-ux-design'],
               ['The Complete App Design Course - UX, UI and Design Thinking','https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/'],
               ['UX & Web Design Master Course: Strategy, Design, Development','https://www.udemy.com/course/ux-web-design-master-course-strategy-design-development/'],
               ['The Complete App Design Course - UX, UI and Design Thinking','https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/'],
               ['DESIGN RULES: Principles + Practices for Great UI Design','https://www.udemy.com/course/design-rules/'],
               ['Become a UX Designer by Udacity','https://www.udacity.com/course/ux-designer-nanodegree--nd578'],
               ['Adobe XD Tutorial: User Experience Design Course [Free]','https://youtu.be/68w2VwalD5w'],
               ['Adobe XD for Beginners [Free]','https://youtu.be/WEljsc2jorI'],
               ['Adobe XD in Simple Way','https://learnux.io/course/adobe-xd']]
cloud_course = [['AWS Certified Solutions Architect - Associate 2021 (PASS THE EXAM!)[Paid]','https://www.udemy.com/course/aws-certified-solutions-architect-associate/'],
                ['Google Cloud Professional Cloud Architect[Paid]','https://www.udemy.com/course/google-cloud-professional-cloud-architect/'],
                ['Microsoft Certified: Azure Fundamentals[Free]','https://learn.microsoft.com/en-us/certifications/azure-fundamentals/'],
                ['AWS Certified Cloud Practitioner - 2021[Paid]','https://www.udemy.com/course/aws-certified-cloud-practitioner/'],
                ['Cloud Computing Concepts: Part 1[Free]','https://www.coursera.org/learn/cloud-computing'],
                ['Architecting with Google Cloud Platform Specialization[Paid]','https://www.coursera.org/specializations/cloud-architecture'],
                ['Kubernetes for Developers[Paid]','https://www.udemy.com/course/kubernetes-for-developers/'],
                ['Docker and Kubernetes: The Complete Guide[Paid]','https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/'],
                ['Google Cloud Platform Fundamentals: Core Infrastructure[Paid]','https://www.coursera.org/learn/google-cloud-fundamentals'],
                ['Mastering Cloud Computing[Paid]','https://www.udemy.com/course/mastering-cloud-computing/']]
cybersecurity_course = [['The Complete Cyber Security Course: Hackers Exposed![Paid]','https://www.udemy.com/course/the-complete-cyber-security-course-hackers-exposed/'],
                        ['Certified Ethical Hacker (CEH) by EC-Council[Paid]','https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/'],
                        ['CompTIA Security+ Certification[Paid]','https://www.udemy.com/course/comptia-security-plus-sy0-501/'],
                        ['Cybersecurity for Business[Paid]','https://www.coursera.org/learn/cyber-security-business'],
                        ['Complete Cyber Security Bootcamp[Paid]','https://www.udemy.com/course/complete-cyber-security-bootcamp/'],
                        ['Practical Ethical Hacking - The Complete Course[Paid]','https://www.udemy.com/course/practical-ethical-hacking/'],
                        ['Mastering Cybersecurity and Penetration Testing[Paid]','https://www.udemy.com/course/mastering-cybersecurity-penetration-testing/'],
                        ['Network Security Basics[Free]','https://www.coursera.org/learn/network-security-basics'],
                        ['Introduction to Cyber Security Specialization[Paid]','https://www.coursera.org/specializations/intro-cyber-security'],
                        ['AWS Certified Security Specialty[Paid]','https://www.udemy.com/course/aws-certified-security-specialty/']]
data_engineering_course = [['Data Engineering with Google Cloud[Paid]','https://www.coursera.org/professional-certificates/data-engineering-google-cloud'],
                           ['ETL and Data Pipelines with Shell, Airflow and Kafka[Paid]','https://www.udemy.com/course/etl-and-data-pipelines-with-shell-airflow-and-kafka/'],
                           ['Data Engineering Nanodegree by Udacity[Paid]','https://www.udacity.com/course/data-engineer-nanodegree--nd027'],
                           ['Building Data Engineering Pipelines[Paid]','https://www.udemy.com/course/building-data-engineering-pipelines/'],
                           ['SQL for Data Engineering[Paid]','https://www.udemy.com/course/sql-for-data-engineering/'],
                           ['Master Data Engineering with Python[Paid]','https://www.udemy.com/course/master-data-engineering-with-python/'],
                           ['Big Data Analysis with Spark and Hadoop[Paid]','https://www.udemy.com/course/big-data-analysis-with-spark-and-hadoop/'],
                           ['Apache Kafka for Data Engineers[Paid]','https://www.udemy.com/course/apache-kafka-for-data-engineers/'],
                           ['Data Engineering with Azure[Paid]','https://www.udemy.com/course/data-engineering-using-azure/'],
                           ['Data Science and Engineering with Python[Paid]','https://www.udemy.com/course/data-science-and-engineering-with-python/']]
devops_course = [['Docker and Kubernetes for Developers[Paid]','https://www.udemy.com/course/docker-and-kubernetes-for-developers/'],
                 ['The Complete DevOps Engineer Course 2.0[Paid]','https://www.udemy.com/course/the-complete-devops-engineer-course-20/'],
                 ['Learning DevOps: Continuously Deliver Better Software[Paid]','https://www.udemy.com/course/learning-devops/'],
                 ['Mastering DevOps with Docker, Jenkins, Kubernetes, and AWS[Paid]','https://www.udemy.com/course/mastering-devops-with-docker-jenkins-kubernetes-and-aws/'],
                 ['DevOps on AWS: A Practical Guide[Paid]','https://www.udemy.com/course/devops-on-aws-a-practical-guide/'],
                 ['Jenkins for Beginners[Paid]','https://www.udemy.com/course/jenkins-for-beginners/'],
                 ['CI/CD with Jenkins and Kubernetes[Paid]','https://www.udemy.com/course/cicd-with-jenkins-and-kubernetes/'],
                 ['Ansible for DevOps[Paid]','https://www.udemy.com/course/ansible-for-devops/'],
                 ['Terraform on Azure[Paid]','https://www.udemy.com/course/terraform-on-azure/'],
                 ['Kubernetes for DevOps Engineers[Paid]','https://www.udemy.com/course/kubernetes-for-devops-engineers/']]
ai_course = [['Artificial Intelligence A-Z: Learn How to Build an AI[Paid]','https://www.udemy.com/course/artificial-intelligence-az/'],
             ['Artificial Intelligence with Python[Paid]','https://www.udemy.com/course/artificial-intelligence-with-python/'],
             ['Introduction to Artificial Intelligence (AI)[Free]','https://www.coursera.org/learn/ai'],
             ['Deep Learning Specialization by Andrew Ng[Paid]','https://www.coursera.org/specializations/deep-learning'],
             ['Natural Language Processing with Deep Learning in Python[Paid]','https://www.udemy.com/course/natural-language-processing-with-deep-learning-in-python/'],
             ['Python for Artificial Intelligence[Paid]','https://www.udemy.com/course/python-for-artificial-intelligence/'],
             ['AI for Everyone[Free]','https://www.coursera.org/learn/ai-for-everyone'],
             ['AI and Machine Learning for Business[Paid]','https://www.udemy.com/course/ai-and-machine-learning-for-business/'],
             ['Reinforcement Learning Specialization[Paid]','https://www.coursera.org/specializations/reinforcement-learning'],
             ['AI Programming with Python[Paid]','https://www.udacity.com/course/ai-programming-python-nanodegree--nd089']]
database_admin_course = [['MySQL for Database Administration[Paid]','https://www.udemy.com/course/mysql-for-database-administration/'],
                         ['Oracle SQL and PL/SQL for Developers[Paid]','https://www.udemy.com/course/oracle-sql-and-plsql-for-developers/'],
                         ['Microsoft SQL Server for Beginners[Paid]','https://www.udemy.com/course/microsoft-sql-server-for-beginners/'],
                         ['PostgreSQL: Learn PostgreSQL Database from Scratch[Paid]','https://www.udemy.com/course/postgresql-learn-postgresql-database-from-scratch/'],
                         ['Database Management for Beginners[Paid]','https://www.udemy.com/course/database-management-for-beginners/'],
                         ['Mastering SQL for Data Analytics[Paid]','https://www.udemy.com/course/mastering-sql-for-data-analytics/'],
                         ['MongoDB for Developers[Paid]','https://www.udemy.com/course/mongodb-for-developers/'],
                         ['SQL Server Database Administration[Paid]','https://www.udemy.com/course/sql-server-database-administration/'],
                         ['Mastering PostgreSQL for Data Analysis[Paid]','https://www.udemy.com/course/mastering-postgresql-for-data-analysis/'],
                         ['Database Management with Oracle[Paid]','https://www.udemy.com/course/database-management-with-oracle/']]
networking_course = [['CCNA 200-301: The Complete Guide to Getting Certified[Paid]','https://www.udemy.com/course/ccna-200-301-the-complete-guide-to-getting-certified/'],
                     ['CompTIA Network+ (N10-007) Cert Prep[Paid]','https://www.udemy.com/course/comptia-network-plus-n10-007-cert-prep/'],
                     ['Cisco Networking Basics[Free]','https://www.udemy.com/course/cisco-networking-basics/'],
                     ['TCP/IP Networking Essentials[Paid]','https://www.udemy.com/course/tcpip-networking-essentials/'],
                     ['Networking Fundamentals[Free]','https://www.coursera.org/learn/networking-basics'],
                     ['Certified Information Systems Security Professional (CISSP)[Paid]','https://www.udemy.com/course/cissp-certification/'],
                     ['Network Configuration & Troubleshooting[Paid]','https://www.udemy.com/course/network-configuration-troubleshooting/'],
                     ['Introduction to Networking[Free]','https://www.coursera.org/learn/intro-to-networking'],
                     ['Advanced Networking with Python[Paid]','https://www.udemy.com/course/advanced-networking-with-python/'],
                     ['CompTIA Network+ Certification[Paid]','https://www.udemy.com/course/comptia-network-plus-certification/']]
business_intelligence_course = [['Data Visualization with Tableau[Paid]','https://www.udemy.com/course/data-visualization-with-tableau/'],
                                ['Power BI Essentials[Paid]','https://www.udemy.com/course/power-bi-essentials/'],
                                ['Business Intelligence Concepts, Tools, and Applications[Paid]','https://www.udemy.com/course/business-intelligence-tools-and-applications/'],
                                ['Data Visualization and Dashboard Design[Paid]','https://www.coursera.org/learn/data-visualization-dashboard-design'],
                                ['Mastering Business Intelligence with Power BI[Paid]','https://www.udemy.com/course/mastering-business-intelligence-with-power-bi/'],
                                ['SQL for Business Analytics[Paid]','https://www.udemy.com/course/sql-for-business-analytics/'],
                                ['Power BI for Beginners[Paid]','https://www.udemy.com/course/power-bi-for-beginners/'],
                                ['Business Intelligence with Python[Paid]','https://www.udemy.com/course/business-intelligence-with-python/'],
                                ['Business Intelligence Fundamentals[Paid]','https://www.udemy.com/course/business-intelligence-fundamentals/'],
                                ['Advanced Business Intelligence with Power BI[Paid]','https://www.udemy.com/course/advanced-business-intelligence-with-power-bi/']]
game_dev_course = [['Game Development with Unity[Paid]','https://www.udemy.com/course/game-development-with-unity/'],
                   ['Learn C++ Game Development[Paid]','https://www.udemy.com/course/cplusplus-game-development/'],
                   ['Unreal Engine 4: The Complete Beginner\'s Course[Paid]','https://www.udemy.com/course/unreal-engine-4-the-complete-beginners-course/'],
                   ['Unity Game Development: Make a 2D Game from Scratch[Paid]','https://www.udemy.com/course/unity-game-development-make-a-2d-game-from-scratch/'],
                   ['Game Design and Development with Unity[Paid]','https://www.udemy.com/course/game-design-and-development-with-unity/'],
                   ['Complete C# Unity Game Developer 2D[Paid]','https://www.udemy.com/course/unitycourse/'],
                   ['Game Programming in Unity[Paid]','https://www.udemy.com/course/game-programming-in-unity/'],
                   ['Mastering Game Development with Unreal Engine[Paid]','https://www.udemy.com/course/mastering-game-development-with-unreal-engine/'],
                   ['Introduction to Unity for Game Development[Paid]','https://www.udemy.com/course/unity-game-development/'],
                   ['Game Development with C++[Paid]','https://www.udemy.com/course/game-development-with-cplusplus/']]
bi_course = [
    ['Business Intelligence Concepts, Tools, and Applications', 'https://www.coursera.org/learn/business-intelligence-tools'],
    ['Microsoft Power BI Desktop for Business Intelligence [Free]', 'https://youtu.be/TmNAJxyud_w'],
    ['Data Visualization with Power BI', 'https://www.udemy.com/course/data-visualization-with-power-bi/'],
    ['Tableau 2023 A-Z: Hands-On Tableau Training for Data Science', 'https://www.udemy.com/course/tableau10/'],
    ['Business Analytics Specialization - Wharton', 'https://www.coursera.org/specializations/business-analytics'],
    ['Qlik Sense for Beginners', 'https://www.udemy.com/course/qlik-sense-data-visualization-for-beginners/'],
    ['Looker for Business Intelligence [Free]', 'https://cloud.google.com/learn/what-is-looker'],
    ['Business Intelligence with Excel', 'https://www.udemy.com/course/microsoft-excel-data-analysis-dashboard-reporting/'],
    ['Metabase: Open Source Business Intelligence Tool [Free]', 'https://www.metabase.com/learn/'],
    ['Power BI Data Analyst Professional Certificate', 'https://www.coursera.org/professional-certificates/power-bi-data-analyst']
]
db_admin_course = [
    ['Database Management Essentials by Coursera', 'https://www.coursera.org/learn/database-management'],
    ['Oracle SQL Database Administration', 'https://www.udemy.com/course/oracle-database-12c-sql-fundamentals/'],
    ['Microsoft SQL Server for Beginners [Free]', 'https://youtu.be/7GVFYtIJstg'],
    ['MySQL Database Administration', 'https://www.udemy.com/course/mysql-database-administration-mysql-dba-for-beginners/'],
    ['Database Administration and SQL Language Basics', 'https://www.edx.org/course/database-systems'],
    ['PostgreSQL Administration Essentials', 'https://www.udemy.com/course/postgresql-administration/'],
    ['MongoDB Basics [Free]', 'https://learn.mongodb.com/paths/basics'],
    ['Database Design and Data Management', 'https://www.coursera.org/learn/database-design'],
    ['SQL for Data Science', 'https://www.coursera.org/learn/sql-for-data-science'],
    ['IBM Certified Database Administrator Course', 'https://www.coursera.org/learn/introduction-to-databases-ibm']
]

resume_videos = ['https://youtu.be/y8YH0Qbu5h4','https://youtu.be/J-4Fv8nq1iA',
                 'https://youtu.be/yp693O87GmM','https://youtu.be/UeMmCex9uTU',
                 'https://youtu.be/dQ7Q8ZdnuN0','https://youtu.be/HQqqQx5BCFY',
                 'https://youtu.be/CLUsplI4xMU','https://youtu.be/pbczsLkv7Cc']

interview_videos = ['https://youtu.be/Ji46s5BHdr0','https://youtu.be/seVxXHi2YMs',
                    'https://youtu.be/9FgfsLa_SmY','https://youtu.be/2HQmjLu-6RQ',
                    'https://youtu.be/DQd_AlIvHUw','https://youtu.be/oVVdezJ0e7w'
                    'https://youtu.be/JZK1MZwUyUU','https://youtu.be/CyXLhHQS3KY']